//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Sources/Model/swift_echo_server.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate EchoService_EchoServiceClient, then call methods of this protocol to make API calls.
public protocol EchoService_EchoServiceClientProtocol {
  func say(_ request: EchoService_EchoRequest, callOptions: CallOptions?) -> UnaryCall<EchoService_EchoRequest, EchoService_EchoRespone>
}

public final class EchoService_EchoServiceClient: GRPCClient, EchoService_EchoServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the EchoService.EchoService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Sends a greeting.
  ///
  /// - Parameters:
  ///   - request: Request to send to say.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func say(_ request: EchoService_EchoRequest, callOptions: CallOptions? = nil) -> UnaryCall<EchoService_EchoRequest, EchoService_EchoRespone> {
    return self.makeUnaryCall(path: "/EchoService.EchoService/say",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol EchoService_EchoServiceProvider: CallHandlerProvider {
  /// Sends a greeting.
  func say(request: EchoService_EchoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<EchoService_EchoRespone>
}

extension EchoService_EchoServiceProvider {
  public var serviceName: String { return "EchoService.EchoService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "say":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.say(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload` for request and response messages
extension EchoService_EchoRequest: GRPCProtobufPayload {}
extension EchoService_EchoRespone: GRPCProtobufPayload {}

